services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/faq_system
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: "none"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    logging:
      driver: "none"

volumes:
  mongodb_data: